// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mapwalk
DataFrame mapwalk(DataFrame spt, DataFrame sp, NumericVector all_vec, int epsg);
RcppExport SEXP _mapalib_mapwalk(SEXP sptSEXP, SEXP spSEXP, SEXP all_vecSEXP, SEXP epsgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type spt(sptSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type sp(spSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type all_vec(all_vecSEXP);
    Rcpp::traits::input_parameter< int >::type epsg(epsgSEXP);
    rcpp_result_gen = Rcpp::wrap(mapwalk(spt, sp, all_vec, epsg));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mapalib_mapwalk", (DL_FUNC) &_mapalib_mapwalk, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mapalib(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
